site_name: 'APP-CMS Server'
theme: 'material'
version: '1.3.0'
extra:
  palette:
    primary: 'red'
    accent: 'red'
  social:
    - type: 'github'
      link: 'https://github.com/appcms/server'
    - type: 'twitter'
      link: 'https://twitter.com/app_agentur'
    - type: 'home'
      link: 'http://www.das-app-cms.de'
  disqus: 'appcms'
markdown_extensions:
  - admonition
  - codehilite(linenums=true)
  - toc(permalink=true)
  - footnotes
pages:
- Allgemein:
    - Einführung: 'index.md'
    - Installation: 'allgemein/installation.md'
    - Erste Schritte: 'allgemein/ersteschritte.md'
    - Architektur: 'allgemein/architektur.md'
    - Konsolenbefehle: 'allgemein/konsole.md'
    - Schnittstelle/API: 'allgemein/schnittstelle.md'
- Konfiguration:
    - System: 'konfiguration/system.md'
    - Entitäten: 'konfiguration/entitaeten.md'
    - Standard-Feldtypen: 'konfiguration/standard-feldtypen.md'
    - Benutzerdefinierte Feldtypen: 'konfiguration/benutzerdefinierte-feldtypen.md'
- Anpassung Backend:
    - Events und Hooks: 'backend/events-hooks.md'
    - Erweiterung Standard-Entitäten: 'backend/standard-entitaeten.md'
    - Benutzerdefinierte API-Aufrufe: 'backend/api.md'
    - Benutzerdefinierte Konsolenbefehle: 'backend/konsole.md'
    - Benutzerdefinierte Composer Bibliotheken: 'backend/composer.md'
- Anpassung Frontend:
  - Anpassung UI: 'ui-frontend/ui.md'
  - Benutzerdefiniertes Frontend: 'ui-frontend/frontend.md'
  - Benutzerdefinierte Composer Bibliotheken: 'backend/composer.md'
- Datenbankzugriff:
  - Doctrine Repositories: 'database/repositories.md'
  - Doctrine DQL: 'database/dql.md'
  - Doctrine DBAL: 'database/dbal.md'
