site_name: 'Backend'
theme: 'readthedocs'
version: '1.3.0'
pages:
- Infos: 'index.md'
- Erste Schritte: 'ersteschritte.md'
- Entwicklung:
    - Setup: 'dev_setup.md'
    - Entitäten: 'dev_entities.md'
    - Backend: 'dev_backend.md'
    - Frontend: 'dev_frontend.md'
