site_name: 'APP-CMS Backend'
theme: 'material'
version: '1.3.0'
extra:
  palette:
    primary: 'red'
    accent: 'red'
  social:
    - type: 'github'
      link: 'https://github.com/appcms/backend'
    - type: 'twitter'
      link: 'https://twitter.com/app_agentur'
    - type: 'home'
      link: 'http://www.das-app-cms.de'
  disqus: 'appcms'
markdown_extensions:
  - admonition
  - codehilite(linenums=true)
  - toc(permalink=true)
  - footnotes
pages:
- Allgemein:
    - Einführung: 'index.md'
    - Installation: 'allgemein/installation.md'
    - Erste Schritte: 'allgemein/ersteschritte.md'
    - Architektur: 'allgemein/architektur.md'
    - Konsolenbefehle: 'allgemein/konsole.md'
    - Schnittstelle/API: 'allgemein/schnittstelle.md'
- Entwicklung:
    - Setup: 'entwicklung/setup.md'
    - Entitäten: 'entwicklung/entities.md'
    - Backend: 'entwicklung/backend.md'
    - Frontend: 'entwicklung/frontend.md'
